name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':rocket: Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: ':bug: Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: ':wrench: Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'build'
      - 'perf'
      - 'improvement'
      - 'style'
      - 'test'
  - title: ':hammer_and_wrench: Refactor'
    labels:
      - 'refac'
      - 'refact'
      - 'refactor'
  - title: ':notebook: Docs'
    label: 'docs'
  - title: ':robot: Automation'
    labels:
      - 'auto'
      - 'automation'
      - 'dependencies'
      - 'deps'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
