name: CI UI
on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: "./node_modules"
          key: modules-${{ hashFiles('./yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  tests:
    name: Tests and Coverage
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - name: Run Tests
        run: yarn test:coverage
      - name: Upload Coverage Report (Codecov)
        run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: Run ESLint
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn lint

  build:
    name: Build Package
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn build
