name: CI UI
on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true

jobs:
  # Only run CI from unprotected branches (avoid CI for backporting)
  check_branch:
    name: Check origin branch
    if: ${{ (github.head_ref != 'main') && (github.head_ref != 'develop') && !startsWith(github.head_ref, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Should run CI based on origin branch? - ${{ steps.should_run.outputs.should_run }}

  dependencies:
    name: Install dependencies
    needs: check_branch
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: modules-${{ hashFiles('./yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  tests:
    name: Tests and coverage
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - name: Run Tests
        run: yarn test:coverage
      - name: Upload Coverage Report (Codecov)
        run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: Run ESLint
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn lint

  build:
    name: Build package
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn build
