name: CI UI
on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true

jobs:
  check_branch:
    name: 'Check origin branch'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Only run CI from non-protected branches (avoid CI for backporting)
      - name: Check origin branch
        id: should_run
        run: |
          should_run=${{ (github.head_ref != 'main') && (github.head_ref != 'develop') && !startsWith(github.head_ref, 'release') }}
          echo "::set-output name=should_run::$should_run"
      - run: echo Should run PR based on origin branch? - ${{ steps.should_run.outputs.should_run }}
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}

  tests:
    name: 'Tests and Coverage'
    needs: check_branch
    if: ${{ needs.check_branch.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test:coverage
      - name: Upload Coverage Report (Codecov)
        run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: 'Run ESLint'
    needs: check_branch
    if: ${{ needs.check_branch.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - run: yarn lint
