name: Deploy Functions
on:
  workflow_call:
    inputs:
      aws_profile:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      short_env:
        required: true
        type: string
      build_since:
        required: true
        type: string
      branch:
        required: true
        type: string

    secrets:
      NPM_AUTH_TOKEN:
        required: true
      AWS_OPS_BUCKET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: 'Deploy Functions'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      AWS_OPS_BUCKET: ${{ secrets.AWS_OPS_BUCKET }}

    steps:
      - uses: actions/checkout@v2
        with:
          branch: ${{ inputs.branch }}
          fetch-depth: 5
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: modules-${{ hashFiles('./yarn.lock') }}

      - name: Setup AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile terraform
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile terraform
          aws configure set region us-east-1 --profile terraform
          aws_assume=($(aws sts assume-role \
              --role-arn "arn:aws:iam::${{ inputs.aws_account_id }}:role/cicd" \
              --role-session-name "ci" \
              --profile terraform \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text))
          aws configure set aws_access_key_id "${aws_assume[0]}" --profile ${{ inputs.aws_profile }}
          aws configure set aws_secret_access_key "${aws_assume[1]}" --profile ${{ inputs.aws_profile }}
          aws configure set aws_session_token "${aws_assume[2]}" --profile ${{ inputs.aws_profile }}

      # https://github.com/aws/aws-cli/issues/5262
      - name: Configure AWS Region
        run: echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - run: lerna bootstrap
      
      - name: Build common packages
        run: lerna run build:common

      - name: Build modified packages
        run: lerna run build --since ${{ inputs.build_since }} --exclude-dependents

      - name: Deploy modified packages
        run: lerna run deploy:${{ inputs.short_env }} --since ${{ inputs.build_since }} --exclude-dependents
