name: Generate Release
on:
  push:
    branches: [main]

jobs:
  generate_release:
    name: Generate and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Generate and publish release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
