name: Generate Release
on:
  push:
    # branches: [main]
    branches: [FA-735]

jobs:
  generate_release:
    name: Generate and publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate and publish release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          commitish: FA-735

      - name: Update major related tag
        uses: haya14busa/action-update-semver@v1
        with:
          tag: ${{ steps.release_drafter.outputs.tag_name }}
          major_version_tag_only: true
