name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print pwd
        run: |
          echo ""
          echo ""
          ls -l

      - uses: './actions/git-flow-enforcer'
        name: my action
