name: test
on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: './actions/git-flow-enforcer'
        name: my action
